# Use an official Go runtime as a parent image
FROM golang:1.18

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Build the Go application
RUN go mod tidy
RUN go build -o main

# Run the Go application
CMD ["./main"]